setup: &SETUP
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *SETUP
  database: mysparql_dev

test: &TEST
  <<: *SETUP
  database: mysparql_test

production:
  <<: *SETUP
  database: mysparql

cucumber:                                   
  <<: *TEST

